// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package passions is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
*/
package passions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Passions []string `protobuf:"bytes,1,rep,name=passions" json:"passions,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SearchResponse struct {
	Destinations []string `protobuf:"bytes,1,rep,name=destinations" json:"destinations,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SearchRequest)(nil), "passions.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "passions.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for PassionServices service

type PassionServicesClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type passionServicesClient struct {
	cc *grpc.ClientConn
}

func NewPassionServicesClient(cc *grpc.ClientConn) PassionServicesClient {
	return &passionServicesClient{cc}
}

func (c *passionServicesClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/passions.PassionServices/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PassionServices service

type PassionServicesServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterPassionServicesServer(s *grpc.Server, srv PassionServicesServer) {
	s.RegisterService(&_PassionServices_serviceDesc, srv)
}

func _PassionServices_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassionServicesServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passions.PassionServices/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassionServicesServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PassionServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "passions.PassionServices",
	HandlerType: (*PassionServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _PassionServices_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x48, 0x2c, 0x2e, 0xce,
	0xcc, 0xcf, 0x2b, 0x96, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4,
	0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0x01, 0x89, 0x43, 0xd4, 0x29, 0x69, 0x73, 0xf1, 0x06,
	0xa7, 0x26, 0x16, 0x25, 0x67, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x71, 0xc1,
	0xb5, 0x4a, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x06, 0xc1, 0xf9, 0x4a, 0x26, 0x5c, 0x7c, 0x30, 0xc5,
	0xc5, 0x05, 0x40, 0x81, 0x54, 0x21, 0x25, 0x2e, 0x9e, 0x14, 0xa0, 0xae, 0xcc, 0x3c, 0x88, 0xa1,
	0x50, 0x1d, 0x28, 0x62, 0x46, 0xa9, 0x5c, 0xfc, 0x01, 0x10, 0x13, 0x82, 0x21, 0x4e, 0x2c, 0x16,
	0x0a, 0xe2, 0x62, 0x83, 0x18, 0x24, 0x24, 0xae, 0x07, 0x33, 0x5d, 0x0f, 0xc5, 0x1d, 0x52, 0x12,
	0x98, 0x12, 0x10, 0x3b, 0x95, 0x44, 0x9b, 0x2e, 0x3f, 0x99, 0xcc, 0xc4, 0xaf, 0xc4, 0xa5, 0x5f,
	0x66, 0xa8, 0x5f, 0x0c, 0x96, 0xb3, 0x62, 0xd4, 0x4a, 0x62, 0x03, 0x7b, 0xc8, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0xbb, 0xdc, 0x8c, 0x09, 0x01, 0x00, 0x00,
}
